force-app/main/default/objects/Area_Code__mdt/Area_Code__mdt.object-meta.xml
<CustomObject>
    <description>https://docs.google.com/spreadsheets/d/1cC6I38y_xA9wt4JXuAUjeGi153JyrnNSxCs1VCXqO80/edit?usp=sharing
Gives Sate, Country, and timezone given an area code in the &#39;1&#39; Country Dial Code</description>
    <label>Area Code</label>
    <pluralLabel>Area Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Area_Code__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <inlineHelpText>2 letter Country Code</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <default>true</default>
                <label>AF</label>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>DZ</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BY</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BZ</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BT</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area_Code__mdt/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <inlineHelpText>2 letter State Code</inlineHelpText>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
                <default>true</default>
                <label>AL</label>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area_Code__mdt/fields/Timezone_Offset__c.field-meta.xml
<CustomField>
    <fullName>Timezone_Offset__c</fullName>
    <description>Guess timezone based on region of Area Code</description>
    <inlineHelpText>Best guess at timezone of area code</inlineHelpText>
    <label>Timezone Offset</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PhoneParsingService.cls
public class PhoneParsingService {

    public String extension = null;

    String beforeExtension = null;
    String beforeExtensionClean = null;

    String rawPhone = null;
    public String countryDialCode = null;
    public String tenDigit = null;
    public String areaCode = null;
    public String lineNumber = null;
    
    public String canonicalPhone = null;

    public String countryIsoCode = null;
    public String stateIsoCode = null;
    public Boolean isUsNumber = false;
    public Boolean isValidNumber = false;

    public Integer timezoneOffset = null;

    public PhoneParsingService(String phone) {
        init(phone);
    }

    void init(String Phone) {
        this.rawPhone = phone;
        this.getExtension();
        this.getCountryDialCode();
        this.getCanonicalPhone();
    }

    static String getNumeric(String inString) {
        String answer = '';
        for (String charInString: inString.split('')) {
            if (charInString.isNumeric()) {
                answer += charInString;
            }
        }
        return answer;
    }

    void getExtension() {
        // this will catch seperators such as 'x', 'X', 'ext.'', 'EXT.'
        String toFind = 'x';

        List<String> phoneParts = this.rawPhone.toLowerCase().split(toFind);
        this.beforeExtension = phoneParts[0];
        this.beforeExtensionClean = PhoneParsingService.getNumeric(phoneParts[0]);

        // initialize extension in case it isn't set in if block
        this.extension = null;
        if (phoneParts.size() > 1) {
            phoneParts.remove(0);
            this.extension = PhoneParsingService.getNumeric(String.join(phoneParts, 'x'));
            if (this.extension == '') {
                this.extension = null;
            }
        }
    }

    Boolean isCountryCodeOne() {
        // Phone is in US, Canada, Puerto Rico if it is 10 digits or 11 digits beginning with 1
        return this.beforeExtensionClean.length() == 10 || (this.beforeExtensionClean.length() == 11 && this.beforeExtensionClean.startsWith('1'));
    }

    void getCountryDialCode() {
        if (this.isCountryCodeOne()) {
            this.countryDialCode = '1';
            
            if (this.beforeExtensionClean.length() == 10) {
                this.tenDigit = this.beforeExtensionClean;
            }
            else {
                this.tenDigit = this.beforeExtensionClean.substring(1, 11);
            }
            this.areaCode = this.tenDigit.substring(0, 3);
            this.lineNumber = this.tenDigit.substring(3, 10);
            List<Area_Code__mdt> areaCodeMdtList = [SELECT State_Code__c, Country_Code__c, Timezone_Offset__c FROM Area_Code__mdt WHERE Label = :this.areaCode LIMIT 1];
            if (areaCodeMdtList.size() != 0) {
                Area_Code__mdt areaCodeMdt = areaCodeMdtList.get(0);
                this.isValidNumber = true;
                this.countryIsoCode = areaCodeMdt.Country_Code__c;
                if (this.countryIsoCode == 'US') {
                    this.isUsNumber = true;
                }
                this.stateIsoCode = areaCodeMdt.State_Code__c;
                if (areaCodeMdt.Timezone_Offset__c != null) {
                    this.timezoneOffset = Integer.valueOf(areaCodeMdt.Timezone_Offset__c);
                }
            }
        }
    }

    void getCanonicalPhone() {
        if (this.areaCode != null) {
            this.canonicalPhone = this.countryDialCode + ' ' + this.areaCode + ' ' + this.lineNumber;
            if (this.extension != null) {
                this.canonicalPhone += ' x ' + this.extension;
            }
        }
    }
}